const LANG_DICT = {
    en: {
        title: "🏖️ Shoreline - Coastal Fun & Dining Guide",
        subtitle: "Discover the best beaches, explore their local amenities, and find premium spots to eat right by the waves!",
        sidebar_settings: "📍 Location Explorer",
        lang_lbl: "🌐 Language / Γλώσσα",
        categories_title: "Select Beach Profiles:",
        categories_opt: {
            "Sandy Beaches 🏖️": "natural_feature",
            "Coastal Attractions 🌊": "tourist_attraction"
        },
        keyword_lbl: "Beach Amenity Sub-Filter:",
        keyword_ph: "e.g., Organized, Secluded, Surf, Shallow",
        keyword_help: "Refine beach search results with specific features.",
        loc_mode_lbl: "Location Selection Mode:",
        loc_mode_opt: ["🔍 Type a Coastal Area / Landmark", "⌨️ Input Coordinates Directly"],
        addr_lbl: "Enter Coastal Destination:",
        addr_ph: "e.g., Vouliagmeni, Athens",
        addr_success: "🎯 Destination Locked:",
        addr_error: "❌ Could not find location. Check your spelling!",
        addr_info: "💡 Type an address or click anywhere on the interactive map grid.",
        coord_lbl: "Target Coordinates (Lat, Lng):",
        coord_help: "Clicking the map or pasting coordinates updates this field instantly.",
        coord_error: "Format error. Please use: latitude, longitude",
        radius_lbl: "Beach Scan Distance (Meters)",
        food_radius_lbl: "Dining Scan Distance (Meters)",
        btn_run: "🏖️ Find Coastal Fun!",
        btn_spinner: "Scouting beaches...",
        no_results: "📭 No beaches found matching your active criteria in this area.",
        resource_lbl: "### 📊 App Resource Monitor",
        limit_lbl: "Daily Usage Check:",
        limit_reached: "🚨 Daily Search Cap Reached! Come back tomorrow for more adventures.",
        lens_lbl: "### 🛠️ View Filter Options",
        lens_choices: ["🌟 Show Top Dining Spots Near Beaches", "♿ Show Highly Accessible Beach zones"],
        peak_opp_lbl: "Top Beach Experience Rating",
        peak_opp_delta: "Highly Rated Beach",
        peak_dom_lbl: "Crowd-Favorite Spot",
        peak_dom_delta: "Top Choice Spot",
        map_init_info: "💡 Map active! Click somewhere or type a coastal city on the sidebar, then run the search to reveal options.",
        map_title: "🗺️ Coastal Fun Map Explorer",
        map_epicenter_pop: "📍 <b>Your Basecamp Spot</b>",
        map_epicenter_tt: "Search Center (Click map to shift basecamp)",
        map_popup_status: "Status",
        map_popup_rating: "Beach Rating:",
        map_popup_reviews: "Total Reviews:",
        map_popup_opp_idx: "Fun Score:",
        map_popup_dom_idx: "Popularity Index:",
        legend_title: "### 📋 Beach & Operations Legend Matrix",
        leg1_gap: "<strong>👑 Elite Beachfront</strong><br><small>Highly reviewed and perfect crystal-clear coastal experiences.</small>",
        leg2_gap: "<strong>🌊 Local Favorite</strong><br><small>Great reviews and regular foot traffic from locals and tourists alike.</small>",
        leg3_gap: "<strong>🛶 Secluded Spot</strong><br><small>Hidden gems with fewer reviews but perfect for quiet getaways.</small>",
        leg_hours: "<strong>⏰ Operational Codes</strong><br><small>🟢 <b>Open:</b> Accessible right now.<br>🔴 <b>Closed:</b> Closed / Out of season.<br>⚪ <b>N/A:</b> Listing lacks timing data.</small>",
        matrix_title: "📊 Beach Dining & Activity Matrix",
        col_rank: "Rank",
        col_establishment: "Beach Name",
        col_status: "Access Status",
        col_profile: "Vibe Rating",
        col_rating: "Rating",
        col_reviews: "Reviews",
        col_price: "Price Tier",
        col_gap: "Experience Score",
        col_deficit: "Crowd Score",
        col_dom: "Vibe Index",
        col_site: "Maps Navigation",
        col_site_btn: "Navigate 🧭",
        col_action: "Click Row to Select",
        col_action_btn: "👉 View Details",
        col_amenities: "Amenities",
        method_title: "ℹ️ Beach Amenities & Restaurant Ranking",
        method_text: "**♿ Accessibility Indicators:**\n* Checks venue attributes for parameters such as `wheelchair_accessible_entrance`. Look for the symbols in the analytical table columns to pick optimized spots.\n\n**🍹 Local Services & Amenities:**\n* Automatically parses keywords like restaurant availability, rentals, sunbeds, bars, toilets, and parking spaces right beside each individual beachfront.\n\n**🍴 Top {limit} Restaurants Ranking Formula:**\n* Each beach displays its top {limit} nearby restaurants ranked by composite score:\n  - **Rating (50%)**: Higher star ratings weighted heavily\n  - **Reviews (30%)**: More reviews indicate reliability and popularity\n  - **Price Level (20%)**: Lower prices weighted favorably\n* Formula: `Score = (Rating/5 × 0.5) + (log(Reviews+1)/log(Max) × 0.3) + ((5-Price)/4 × 0.2)`\n",
        strat_rank_1: "👑 Elite Beachfront",
        strat_rank_2: "🌊 Local Favorite",
        strat_rank_3: "🛶 Secluded Escape",
        strat_rank_4: "⚓ Standard Shore",
        status_open: "🟢 Open",
        status_closed: "🔴 Closed",
        status_temp_closed: "⏳ Temp. Unavailable",
        status_perm_closed: "🚫 Perm. Closed",
        status_na: "⚪ N/A",
        in_business: " ✅ Accessible",
        out_of_business: " ⚠️ Closed",
        na_business: " ❌ N/A",
        lens_choices_title: "Choose Entertainment Angle:",
        find_market_gaps: "🌟 Show Top Dining Spots Near Beaches",
        find_market_leaders: "♿ Show Highly Accessible Beach zones",
        strat_profile_header: "🎯 Coastal Vibe Definitions",
        strat_profile_text: "How we rank and classify coastal spots for your entertainment:",
        strat_1_desc: "Top-tier premium destinations with pristine reviews.",
        strat_2_desc: "Incredible atmospheres with highly rated crowd retention.",
        strat_3_desc: "Uncrowded spots perfect for relaxing.",
        strat_4_desc: "Basic beachfront areas with limited local facilities.",
        select_beach_prompt: "**Select a beach directly from the table above to view details & nearby restaurants ⬇️**",
        select_beach_info: "💡 Select a beach in the table to display its details, reviews, and top dining spots.",
        phone_label: "Phone",
        website_label: "Website",
        visit_website: "Visit Website",
        not_available: "Does not exist"
    },
    el: {
        title: "🏖️ Shoreline - Παραθαλάσσιος Οδηγός Διασκέδασης & Φαγητού",
        subtitle: "Ανακαλύψτε τις καλύτερες παραλίες, δείτε τις παροχές τους και βρείτε κορυφαία εστιατόρια ακριβώς δίπλα στο κύμα!",
        sidebar_settings: "📍 Εξερεύνηση Τοποθεσίας",
        lang_lbl: "🌐 Γλώσσα / Language",
        categories_title: "Επιλογή Προφίλ Παραλίας:",
        categories_opt: {
            "Φυσικές Παραλίες 🏖️": "natural_feature",
            "Παραθαλάσσια Αξιοθέατα 🌊": "tourist_attraction"
        },
        keyword_lbl: "Φίλτρο Παροχών Παραλίας:",
        keyword_ph: "π.χ., Οργανωμένη, Ερημική, Surf, Ρηχά",
        keyword_help: "Περιορίστε τα αποτελέσματα με συγκεκριμένα χαρακτηριστικά.",
        loc_mode_lbl: "Μέθοδος Επιλογής Τοποθεσίας:",
        loc_mode_opt: ["🔍 Πληκτρολόγηση Παραθαλάσσιας Περιοχής", "⌨️ Απευθείας Εισαγωγή Συντεταγμένων"],
        addr_lbl: "Εισάγετε Παραθαλάσσιο Προορισμό:",
        addr_ph: "π.χ., Βουλιαγμένη, Αθήνα",
        radius_lbl: "Ακτίνα Αναζήτησης Παραλίας (Μέτρα)",
        food_radius_lbl: "Ακτίνα Αναζήτησης Εστίασης (Μέτρα)",
        btn_run: "🏖️ Εύρεση Παραθαλάσσιας Διασκέδασης!",
        btn_spinner: "Αναζήτηση παραλιών...",
        no_results: "📭 Δεν βρέθηκαν παραλίες που να ταιριάζουν με τα κριτήριά σας σε αυτή την περιοχή.",
        resource_lbl: "### 📊 Παρακολούθηση Πόρων",
        limit_lbl: "Ημερήσια Χρήση Ορίου:",
        lens_choices_title: "Επιλέξτε Γωνία Προβολής:",
        lens_choices: ["🌟 Εμφάνιση Κορυφαίων Εστιατορίων Κοντά σε Παραλίες", "♿ Εμφάνιση Παραλιών με Πλήρη Προσβασιμότητα"],
        matrix_title: "📊 Πίνακας Παραλιών & Τοπικής Εστίασης",
        phone_label: "Τηλέφωνο",
        website_label: "Ιστοσελίδα",
        visit_website: "Μετάβαση στον ιστότοπο",
        not_available: "Δεν υπάρχει"
    }
}
export { LANG_DICT };