# ==========================================
# TRANSLATION & LOCALIZATION ENGINE DATA
# ==========================================

LANG_DICT = {
    "en": {
        "title": "🏖️ Shoreline - Coastal Fun & Dining Guide",
        "subtitle": "Discover the best beaches, explore their local amenities, and find premium spots to eat right by the waves!",
        "sidebar_settings": "📍 Location Explorer",
        "lang_lbl": "🌐 Language / Γλώσσα",
        "categories_title": "Select Beach Profiles:",
        "categories_opt": {
            "Sandy Beaches 🏖️": "natural_feature",
            "Coastal Attractions 🌊": "tourist_attraction"
        },
        "keyword_lbl": "Beach Amenity Sub-Filter:",
        "keyword_ph": "e.g., Organized, Secluded, Surf, Shallow",
        "keyword_help": "Refine beach search results with specific features.",
        "loc_mode_lbl": "Location Selection Mode:",
        "loc_mode_opt": ["🔍 Type a Coastal Area / Landmark", "⌨️ Input Coordinates Directly"],
        "addr_lbl": "Enter Coastal Destination:",
        "addr_ph": "e.g., Vouliagmeni, Athens",
        "addr_success": "🎯 Destination Locked:",
        "addr_error": "❌ Could not find location. Check your spelling!",
        "addr_info": "💡 Type an address or click anywhere on the interactive map grid.",
        "coord_lbl": "Target Coordinates (Lat, Lng):",
        "coord_help": "Clicking the map or pasting coordinates updates this field instantly.",
        "coord_error": "Format error. Please use: latitude, longitude",
        "radius_lbl": "Beach Scan Distance (Meters)",
        "food_radius_lbl": "Dining Scan Distance (Meters)",
        "btn_run": "🏖️ Find Coastal Fun!",
        "btn_spinner": "Scouting beaches and local dining hotspots...",
        "no_results": "📭 No beaches found matching your active criteria in this area.",
        "resource_lbl": "### 📊 App Resource Monitor",
        "limit_lbl": "Daily Usage Check:",
        "limit_reached": "🚨 Daily Search Cap Reached! Come back tomorrow for more adventures.",
        "lens_lbl": "### 🛠️ View Filter Options",
        "lens_choices": ["🌟 Show Top Dining Spots Near Beaches", "♿ Show Highly Accessible Beach zones"],
        "peak_opp_lbl": "Top Beach Experience Rating",
        "peak_opp_delta": "Highly Rated Beach",
        "peak_dom_lbl": "Crowd-Favorite Spot",
        "peak_dom_delta": "Top Choice Spot",
        "map_init_info": "💡 Map active! Click somewhere or type a coastal city on the sidebar, then run the search to reveal options.",
        "map_title": "🗺️ Coastal Fun Map Explorer",
        "map_epicenter_pop": "📍 <b>Your Basecamp Spot</b>",
        "map_epicenter_tt": "Search Center (Click map to shift basecamp)",
        "map_popup_status": "Status",
        "map_popup_rating": "Beach Rating:",
        "map_popup_reviews": "Total Reviews:",
        "map_popup_opp_idx": "Fun Score:",
        "map_popup_dom_idx": "Popularity Index:",
        "legend_title": "### 📋 Beach & Operations Legend Matrix",
        "leg1_gap": "<strong>👑 Elite Beachfront</strong><br><small>Highly reviewed and perfect crystal-clear coastal experiences.</small>",
        "leg2_gap": "<strong>🌊 Local Favorite</strong><br><small>Great reviews and regular foot traffic from locals and tourists alike.</small>",
        "leg3_gap": "<strong>🛶 Secluded Spot</strong><br><small>Hidden gems with fewer reviews but perfect for quiet getaways.</small>",
        "leg_hours": "<strong>⏰ Operational Codes</strong><br><small>🟢 <b>Open:</b> Accessible right now.<br>🔴 <b>Closed:</b> Closed / Out of season.<br>⚪ <b>N/A:</b> Listing lacks timing data.</small>",
        "matrix_title": "📊 Beach Dining & Activity Matrix",
        "col_rank": "Rank",
        "col_establishment": "Beach Name",
        "col_status": "Access Status",
        "col_profile": "Vibe Rating",
        "col_rating": "Rating",
        "col_reviews": "Reviews",
        "col_price": "Price Tier",
        "col_gap": "Experience Score",
        "col_deficit": "Crowd Score",
        "col_dom": "Vibe Index",
        "col_site": "Maps Navigation",
        "col_site_btn": "Navigate 🧭",
        "col_action": "Click Row to Select",
        "col_action_btn": "👉 View Details",
        "col_amenities": "Amenities",
        "method_title": "ℹ️ Beach Amenities & Restaurant Ranking",
        "method_text": """
**♿ Accessibility Indicators:**
* Checks venue attributes for parameters such as `wheelchair_accessible_entrance`. Look for the symbols in the analytical table columns to pick optimized spots.

**🍹 Local Services & Amenities:**
* Automatically parses keywords like restaurant availability, rentals, sunbeds, bars, toilets, and parking spaces right beside each individual beachfront.

**🍴 Top {limit} Restaurants Ranking Formula:**
* Each beach displays its top {limit} nearby restaurants ranked by composite score:
  - **Rating (50%)**: Higher star ratings weighted heavily
  - **Reviews (30%)**: More reviews indicate reliability and popularity
  - **Price Level (20%)**: Lower prices weighted favorably
* Formula: `Score = (Rating/5 × 0.5) + (log(Reviews+1)/log(Max) × 0.3) + ((5-Price)/4 × 0.2)`
""",
        "strat_rank_1": "👑 Elite Beachfront",
        "strat_rank_2": "🌊 Local Favorite",
        "strat_rank_3": "🛶 Secluded Escape",
        "strat_rank_4": "⚓ Standard Shore",
        "status_open": "🟢 Open",
        "status_closed": "🔴 Closed",
        "status_temp_closed": "⏳ Temp. Unavailable",
        "status_perm_closed": "🚫 Perm. Closed",
        "status_na": "⚪ N/A",
        "in_business": " ✅ Accessible",
        "out_of_business": " ⚠️ Closed",
        "na_business": " ❌ N/A",
        "lens_choices_title": "Choose Entertainment Angle:",
        "find_market_gaps": "🌟 Show Top Dining Spots Near Beaches",
        "find_market_leaders": "♿ Show Highly Accessible Beach zones",
        "strat_profile_header": "🎯 Coastal Vibe Definitions",
        "strat_profile_text": "How we rank and classify coastal spots for your entertainment:",
        "strat_1_desc": "Top-tier premium destinations with pristine reviews.",
        "strat_2_desc": "Incredible atmospheres with highly rated crowd retention.",
        "strat_3_desc": "Uncrowded spots perfect for relaxing.",
        "strat_4_desc": "Basic beachfront areas with limited local facilities.",
        "select_beach_prompt": "**Select a beach directly from the table above to view details & nearby restaurants ⬇️**",
        "select_beach_info": "💡 Select a beach in the table to display its details, reviews, and top dining spots.",
        "phone_label": "Phone",
        "website_label": "Website",
        "visit_website": "Visit Website",
        "not_available": "Does not exist"
    },
    "el": {
        "title": "🏖️ Shoreline - Παραθαλάσσιος Οδηγός Διασκέδασης & Φαγητού",
        "subtitle": "Ανακαλύψτε τις καλύτερες παραλίες, δείτε τις παροχές τους και βρείτε κορυφαία εστιατόρια ακριβώς δίπλα στο κύμα!",
        "sidebar_settings": "📍 Εξερεύνηση Τοποθεσίας",
        "lang_lbl": "🌐 Γλώσσα / Language",
        "categories_title": "Επιλογή Προφίλ Παραλίας:",
        "categories_opt": {
            "Φυσικές Παραλίες 🏖️": "natural_feature",
            "Παραθαλάσσια Αξιοθέατα 🌊": "tourist_attraction"
        },
        "keyword_lbl": "Φίλτρο Παροχών Παραλίας:",
        "keyword_ph": "π.χ., Οργανωμένη, Ερημική, Surf, Ρηχά",
        "keyword_help": "Περιορίστε τα αποτελέσματα με συγκεκριμένα χαρακτηριστικά.",
        "loc_mode_lbl": "Μέθοδος Επιλογής Τοποθεσίας:",
        "loc_mode_opt": ["🔍 Πληκτρολόγηση Παραθαλάσσιας Περιοχής", "⌨️ Απευθείας Εισαγωγή Συντεταγμένων"],
        "addr_lbl": "Εισάγετε Παραθαλάσσιο Προορισμό:",
        "addr_ph": "π.χ., Βουλιαγμένη, Αθήνα",
        "addr_success": "🎯 Προορισμός Κλείδωσε:",
        "addr_error": "❌ Αδυναμία εύρεσης τοποθεσίας. Ελέγξτε την ορθογραφία!",
        "addr_info": "💡 Πληκτρολογήστε μια διεύθυνση ή κάντε κλικ οπουδήποτε στον χάρτη.",
        "coord_lbl": "Συντεταγμένες Στόχου (Lat, Lng):",
        "coord_help": "Το κλικ στον χάρτη ή η επικόλληση συντεταγμένων ενημερώνει αυτό το πεδίο αμέσως.",
        "coord_error": "Σφάλμα μορφής. Παρακαλώ χρησιμοποιήστε: γεωγραφικό πλάτος, γεωγραφικό μήκος",
        "radius_lbl": "Ακτίνα Αναζήτησης Παραλίας (Μέτρα)",
        "food_radius_lbl": "Ακτίνα Αναζήτησης Εστίασης (Μέτρα)",
        "btn_run": "🏖️ Εύρεση Παραθαλάσσιας Διασκέδασης!",
        "btn_spinner": "Αναζήτηση παραλιών και τοπικών σημείων εστίασης...",
        "no_results": "📭 Δεν βρέθηκαν παραλίες που να ταιριάζουν με τα κριτήριά σας σε αυτή την περιοχή.",
        "resource_lbl": "### 📊 Παρακολούθηση Πόρων",
        "limit_lbl": "Ημερήσια Χρήση Ορίου:",
        "limit_reached": "🚨 Εξαντλήθηκε το Ημερήσιο Όριο! Δοκιμάστε ξανά αύριο για νέες περιπέτειες.",
        "lens_lbl": "### 🛠️ Φίλτρα Προβολής",
        "lens_choices": ["🌟 Εμφάνιση Κορυφαίων Εστιατορίων Κοντά σε Παραλίες", "♿ Εμφάνιση Παραλιών με Πλήρη Προσβασιμότητα"],
        "peak_opp_lbl": "Κορυφαία Βαθμολογία Παραλίας",
        "peak_opp_delta": "Εξαιρετική Παραλία",
        "peak_dom_lbl": "Δημοφιλές Σημείο",
        "peak_dom_delta": "Κορυφαία Επιλογή",
        "map_init_info": "💡 Ο χάρτης είναι ενεργός! Κάντε κλικ οπουδήποτε ή πληκτρολογήστε μια περιοχή για να ξεκινήσετε.",
        "map_title": "🗺️ Χάρτης Εξερεύνησης Παραλιών",
        "map_epicenter_pop": "📍 <b>Το Σημείο Σας</b>",
        "map_epicenter_tt": "Επίκεντρο Αναζήτησης (Κάντε κλικ στον χάρτη για μετακίνηση)",
        "map_popup_status": "Κατάσταση",
        "map_popup_rating": "Βαθμολογία Παραλίας:",
        "map_popup_reviews": "Σύνολο Κριτικών:",
        "map_popup_opp_idx": "Δείκτης Διασκέδασης:",
        "map_popup_dom_idx": "Δείκτης Δημοφιλίας:",
        "legend_title": "### 📋 Υπόμνημα Χάρτη & Λειτουργίας",
        "leg1_gap": "<strong>👑 Κορυφαία Ακτογραμμή</strong><br><small>Εξαιρετικές κριτικές, ιδανικές για κρυστάλλινες παραθαλάσσιες εμπειρίες.</small>",
        "leg2_gap": "<strong>🌊 Δημοφιλής Παραλία</strong><br><small>Μεγάλη επισκεψιμότητα και εξαιρετικές αξιολογήσεις από ντόπιους.</small>",
        "leg3_gap": "<strong>🛶 Απομονωμένο Καταφύγιο</strong><br><small>Κρυμμένα διαμάντια με λιγότερες κριτικές, ιδανικά για ηρεμία.</small>",
        "leg_hours": "<strong>⏰ Κατάσταση Πρόσβασης</strong><br><small>🟢 <b>Ανοιχτό:</b> Προσβάσιμο αυτή τη στιγμή.<br>🔴 <b>Κλειστό:</b> Εκτός σεζόν / Μη προσβάσιμο.<br>⚪ <b>N/A:</b> Δεν υπάρχουν δεδομένα ωραρίου στη Google.</small>",
        "matrix_title": "📊 Πίνακας Παραλιών & Τοπικής Εστίασης",
        "col_rank": "Κατάταξη",
        "col_establishment": "Όνομα Παραλίας",
        "col_status": "Κατάσταση Πρόσβασης",
        "col_profile": "Στυλ / Vibe",
        "col_rating": "Βαθμολογία",
        "col_reviews": "Κριτικές",
        "col_price": "Κατηγορία Τιμής",
        "col_gap": "Δείκτης Εμπειρίας",
        "col_deficit": "Δείκτης Κίνησης",
        "col_dom": "Vibe Index",
        "col_site": "Πλοήγηση Χαρτών",
        "col_site_btn": "Πλοήγηση 🧭",
        "col_action": "Κλικ για Λεπτομέρειες",
        "col_action_btn": "👉 Προβολή",
        "col_amenities": "Παροχές",
        "method_title": "ℹ️ Επεξήγηση Παροχών & Κατάταξης Εστιατορίων",
        "method_text": """
**♿ Δείκτες Προσβασιμότητας ΑΜΕΑ:**
* Ελέγχει παραμέτρους όπως `wheelchair_accessible_entrance`. Αναζητήστε τα εικονίδια στον πίνακα για να επιλέξετε κατάλληλα σημεία.

**🍹 Τοπικές Παροχές & Υπηρεσίες:**
* Αναλύει αυτόματα keywords για ενοικιάσεις, ξαπλώστρες, beach bars, τουαλέτες και χώρους στάθμευσης ακριβώς δίπλα στην ακτή.

**🍴 Κατάταξη Top {limit} Εστιατορίων:**
* Κάθε παραλία εμφανίζει τα {limit} κορυφαία κοντινά εστιατόρια με σύνθετη βαθμολογία:
  - **Αξιολόγηση (50%)**: Υψηλότερες αξιολογήσεις έχουν μεγαλύτερο βάρος
  - **Αριθμός Κριτικών (30%)**: Περισσότερες κριτικές = αξιοπιστία και δημοτικότητα
  - **Κατηγορία Τιμής (20%)**: Χαμηλότερες τιμές προτιμώνται
* Τύπος: `Score = (Rating/5 × 0.5) + (log(Reviews+1)/log(Max) × 0.3) + ((5-Price)/4 × 0.2)`
""",
        "strat_rank_1": "👑 Κορυφαία Ακτογραμμή",
        "strat_rank_2": "🌊 Δημοφιλής Παραλία",
        "strat_rank_3": "🛶 Απομονωμένο Καταφύγιο",
        "strat_rank_4": "⚓ Απλή Ακτή",
        "status_open": "🟢 Ανοιχτό",
        "status_closed": "🔴 Κλειστό",
        "status_temp_closed": "⏳ Προσωρινά Μη Διαθέσιμο",
        "status_perm_closed": "🚫 Μόνιμα Κλειστό",
        "status_na": "⚪ N/A",
        "in_business": "✅ Προσβάσιμο",
        "out_of_business": "⚠️ Μη Προσβάσιμο",
        "na_business": "⚪ N/A",
        "lens_choices_title": "Επιλέξτε Γωνία Προβολής:",
        "find_market_gaps": "🌟 Εμφάνιση Κορυφαίων Εστιατορίων Κοντά σε Παραλίες",
        "find_market_leaders": "♿ Εμφάνιση Παραλιών με Πλήρη Προσβασιμότητα",
        "strat_profile_header": "🎯 Ορισμοί Παραθαλάσσιου Vibe",
        "strat_profile_text": "Πώς κατηγοριοποιούμε τις παραλίες για τη διασκέδασή σας:",
        "strat_1_desc": "Κορυφαίοι προορισμοί με πεντακάθαρα νερά και άριστες κριτικές.",
        "strat_2_desc": "Εξαιρετική ατμόσφαιρα με υψηλή προτίμηση κοινού.",
        "strat_3_desc": "Ήσυχα σημεία ιδανικά για χαλάρωση μακριά από την κοσμοσυρροή.",
        "strat_4_desc": "Τυπικές παραλίες με βασικές ή περιορισμένες υποδομές.",
        "select_beach_prompt": "**Επιλέξτε μια παραλία απευθείας από τον παραπάνω πίνακα για να δείτε λεπτομέρειες & εστιατόρια ⬇️**",
        "select_beach_info": "💡 Επιλέξτε μια παραλία στον πίνακα για να εμφανιστούν οι λεπτομέρειες, οι κριτικές και τα κοντινά εστιατόρια.",
        "phone_label": "Τηλέφωνο",
        "website_label": "Ιστοσελίδα",
        "visit_website": "Μετάβαση στον ιστότοπο",
        "not_available": "Δεν υπάρχει"
    }
}